In [1]:
!pip list

Package                            Version
---------------------------------- -------------------
absl-py                            1.0.0
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 2.0.3
anaconda-project                   0.9.1
anyio                              2.2.0
appdirs                            1.4.4
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.5
astropy                            4.2.1
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.3.0
autopep8                           1.5.6
Babel                              2.9.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.4
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.2.0
beautifulsoup4                     4.6.0
bitarray                           1.9.2
bkcharts                           0.2
black                              19.10b0
bleach                             3.3.0
bokeh                              2.3.2
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
certifi                            2020.12.5
cffi                               1.14.5
chardet                            4.0.0
click                              7.1.2
cloudpickle                        1.6.0
clyent                             1.2.2
colorama                           0.4.4
comtypes                           1.1.9
conda                              4.10.3
conda-build                        3.21.4
conda-content-trust                0+unknown
conda-package-handling             1.7.3
conda-repo-cli                     1.0.4
conda-token                        0.3.0
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
cryptography                       3.4.7
cycler                             0.10.0
Cython                             0.29.23
cytoolz                            0.11.0
dask                               2021.4.0
datasets                           1.2.1
decorator                          5.0.6
defusedxml                         0.7.1
diff-match-patch                   20200713
dill                               0.3.4
distributed                        2021.4.0
docutils                           0.17
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
filelock                           3.0.12
flake8                             3.9.0
Flask                              1.1.2
fsspec                             0.9.0
future                             0.18.2
gevent                             21.1.2
glob2                              0.7
greenlet                           1.0.0
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.1
idna                               2.10
imagecodecs                        2021.3.31
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 3.10.0
iniconfig                          1.1.1
intervaltree                       3.1.0
ipykernel                          5.3.4
ipython                            7.22.0
ipython-genutils                   0.2.0
ipywidgets                         7.6.3
isort                              5.8.0
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.2
Jinja2                             2.11.3
joblib                             1.0.1
JPype1                             1.3.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.12
jupyter-console                    6.4.0
jupyter-core                       4.7.1
jupyter-packaging                  0.7.12
jupyter-server                     1.4.1
jupyterlab                         3.0.14
jupyterlab-pygments                0.1.2
jupyterlab-server                  2.4.0
jupyterlab-widgets                 1.0.0
jupyterthemes                      0.20.0
keyring                            22.3.0
kiwisolver                         1.3.1
konlpy                             0.5.2
lazy-object-proxy                  1.6.0
lesscpy                            0.15.0
libarchive-c                       2.9
lightgbm                           3.2.1
llvmlite                           0.36.0
locket                             0.2.1
lxml                               4.6.3
MarkupSafe                         1.1.1
matplotlib                         3.3.4
mccabe                             0.6.1
menuinst                           1.4.16
missingno                          0.4.2
mistune                            0.8.4
mkl-fft                            1.3.0
mkl-random                         1.2.1
mkl-service                        2.3.0
mock                               4.0.3
more-itertools                     8.7.0
mpmath                             1.2.1
msgpack                            1.0.2
multipledispatch                   0.6.0
multiprocess                       0.70.12.2
mypy-extensions                    0.4.3
navigator-updater                  0.2.1
nbclassic                          0.2.6
nbclient                           0.5.3
nbconvert                          6.0.7
nbformat                           5.1.3
nest-asyncio                       1.5.1
networkx                           2.5
nltk                               3.6.1
nose                               1.3.7
notebook                           6.3.0
numba                              0.53.1
numexpr                            2.7.3
numpy                              1.20.1
numpydoc                           1.1.0
oauthlib                           3.1.1
olefile                            0.46
openpyxl                           3.0.7
packaging                          20.9
pandas                             1.2.4
pandocfilters                      1.4.3
paramiko                           2.7.2
parso                              0.7.0
partd                              1.2.0
path                               15.1.2
pathlib2                           2.3.5
pathspec                           0.7.0
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             8.2.0
pip                                21.0.1
pkginfo                            1.7.0
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.10.1
prompt-toolkit                     3.0.17
psutil                             5.8.0
ptyprocess                         0.7.0
py                                 1.10.0
pyarrow                            6.0.1
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycurl                             7.43.0.6
pydocstyle                         6.0.0
pyerfa                             1.7.3
pyflakes                           2.2.0
Pygments                           2.8.1
pylint                             2.7.4
pyls-black                         0.4.6
pyls-spyder                        0.3.2
PyNaCl                             1.4.0
pyodbc                             4.0.0-unsupported
pyOpenSSL                          20.0.1
pyparsing                          2.4.7
pyreadline                         2.1
pyrsistent                         0.17.3
PySocks                            1.7.1
pytest                             6.2.3
python-dateutil                    2.8.1
python-jsonrpc-server              0.4.0
python-language-server             0.36.2
pytz                               2021.1
PyWavelets                         1.1.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             5.4.1
pyzmq                              19.0.2
QDarkStyle                         2.8.1
QtAwesome                          1.0.2
qtconsole                          5.0.3
QtPy                               1.9.0
regex                              2021.4.4
requests                           2.25.1
requests-oauthlib                  1.3.0
rope                               0.18.0
rouge-score                        0.0.4
Rtree                              0.9.7
ruamel-yaml-conda                  0.15.100
scikit-image                       0.18.1
scikit-learn                       0.24.1
scipy                              1.6.2
seaborn                            0.11.1
Send2Trash                         1.5.0
setuptools                         52.0.0.post20210125
simplegeneric                      0.8.1
singledispatch                     0.0.0
sip                                4.19.13
six                                1.15.0
sniffio                            1.2.0
snowballstemmer                    2.1.0
sortedcollections                  2.1.0
sortedcontainers                   2.3.0
soupsieve                          2.2.1
Sphinx                             4.0.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.2.5
spyder-kernels                     1.10.2
SQLAlchemy                         1.4.7
statsmodels                        0.12.2
sympy                              1.8
tables                             3.6.1
tblib                              1.7.0
terminado                          0.9.4
testpath                           0.4.4
textdistance                       4.2.1
threadpoolctl                      2.1.0
three-merge                        0.1.1
tifffile                           2021.4.8
tokenizers                         0.10.3
toml                               0.10.2
toolz                              0.11.1
tornado                            6.1
tqdm                               4.49.0
traitlets                          5.0.5
tweepy                             3.10.0
typed-ast                          1.4.2
typing-extensions                  3.7.4.3
ujson                              4.0.2
unicodecsv                         0.14.1
urllib3                            1.26.4
watchdog                           1.0.2
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.36.2
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.12.1
xlrd                               2.0.1
XlsxWriter                         1.3.8
xlwings                            0.23.0
xlwt                               1.3.0
xmltodict                          0.12.0
xxhash                             2.0.2
yapf                               0.31.0
zict                               2.0.0
zipp                               3.4.1
zope.event                         4.5.0
zope.interface                     5.3.0

In [2]:
# %%capture
# !pip install datasets==1.2.1
# !pip install transformers==4.2.0
# !pip install rouge_score

In [1]:
import pandas as pd
from datasets import Dataset
from sklearn.model_selection import train_test_split

In [2]:
train_df = pd.read_csv('~/train_data_newlabel.csv')
train_df

,Unnamed: 0,Original_Filename,Full_Text,FT_Len,Summary,Summary_Len
0,0,15783_819108_2,chief executive officer’s statement the beron...,1147.0,chief executive officer’s statement the berong...,305.0
1,1,15782_819091_2,chief executive officer’s statement the compa...,882.0,chief executive officer’s statement the compan...,319.0
2,2,15787_819176_2,page 6 toledo mining corporation plc annual r...,2203.0,page 6 toledo mining corporation plc annual re...,413.0
3,3,15819_820208_2,review 2005 chief executive’s statement tomki...,505.0,review 2005 chief executive’s statement tomkin...,352.0
4,4,15842_821001_2,7 plc annual report and financial statements ...,1948.0,7 plc annual report and financial statements 2...,352.0
...,...,...,...,...,...,...
2712,2712,324_19904_2,advanced computer software group plc annual r...,1477.0,advanced computer software group plc annual re...,410.0
2713,2713,334_20136_2,14 advanced medical solutions group plc annua...,1458.0,"as we continue the evolution of the group , th...",391.0
2714,2714,335_20160_2,12 13 advanced medical solutions group plc an...,2230.0,"amongst other benefits , we now have direct ac...",415.0
2715,2715,337_20210_2,strategic report continued 12 advanced medica...,1798.0,strategic report continued 12 advanced medical...,399.0
2716,2716,380_22246_2,06 aegis group plc annual report and accounts...,2477.0,we made good progress in increasing our exposu...,390.0

In [21]:
train_df = train_df.drop(['Unnamed: 0', 'Original_Filename', 'FT_Len', 'Summary_Len'], axis=1)
train_df

,Full_Text,Summary
0,chief executive officer’s statement the beron...,chief executive officer’s statement the berong...
1,chief executive officer’s statement the compa...,chief executive officer’s statement the compan...
2,page 6 toledo mining corporation plc annual r...,page 6 toledo mining corporation plc annual re...
3,review 2005 chief executive’s statement tomki...,review 2005 chief executive’s statement tomkin...
4,7 plc annual report and financial statements ...,7 plc annual report and financial statements 2...
...,...,...
2712,advanced computer software group plc annual r...,advanced computer software group plc annual re...
2713,14 advanced medical solutions group plc annua...,"as we continue the evolution of the group , th..."
2714,12 13 advanced medical solutions group plc an...,"amongst other benefits , we now have direct ac..."
2715,strategic report continued 12 advanced medica...,strategic report continued 12 advanced medical...
2716,06 aegis group plc annual report and accounts...,we made good progress in increasing our exposu...

In [3]:
train_df.rename(columns = {'Full_Text': 'article',
                                                        'Summary': 'abstract'}, inplace=True)

In [4]:
train_df

,Unnamed: 0,Original_Filename,article,FT_Len,abstract,Summary_Len
0,0,15783_819108_2,chief executive officer’s statement the beron...,1147.0,chief executive officer’s statement the berong...,305.0
1,1,15782_819091_2,chief executive officer’s statement the compa...,882.0,chief executive officer’s statement the compan...,319.0
2,2,15787_819176_2,page 6 toledo mining corporation plc annual r...,2203.0,page 6 toledo mining corporation plc annual re...,413.0
3,3,15819_820208_2,review 2005 chief executive’s statement tomki...,505.0,review 2005 chief executive’s statement tomkin...,352.0
4,4,15842_821001_2,7 plc annual report and financial statements ...,1948.0,7 plc annual report and financial statements 2...,352.0
...,...,...,...,...,...,...
2712,2712,324_19904_2,advanced computer software group plc annual r...,1477.0,advanced computer software group plc annual re...,410.0
2713,2713,334_20136_2,14 advanced medical solutions group plc annua...,1458.0,"as we continue the evolution of the group , th...",391.0
2714,2714,335_20160_2,12 13 advanced medical solutions group plc an...,2230.0,"amongst other benefits , we now have direct ac...",415.0
2715,2715,337_20210_2,strategic report continued 12 advanced medica...,1798.0,strategic report continued 12 advanced medical...,399.0
2716,2716,380_22246_2,06 aegis group plc annual report and accounts...,2477.0,we made good progress in increasing our exposu...,390.0

In [7]:
test_df = pd.read_csv('~/test_data_newlabel.csv')
test_df

,Unnamed: 0,Original_Filename,Full_Text,FT_Len,Summary,Summary_Len
0,0,30777_904926_2,25695 19 march 2018 3 29 pm proof 7 02 s . c ...,1517.0,25695 19 march 2018 3 29 pm proof 7 02 s .c .h...,334.0
1,1,30783_905079_2,strategic report chief executive’s statement ...,1071.0,strategic report chief executive’s statement 1...,407.0
2,2,30785_905133_2,summary our dedication to providing our clien...,1071.0,summary our dedication to providing our client...,318.0
3,3,30785_905134_2,"q a with ceo , david miles 92 percent of tena...",838.0,"q a with ceo , david miles 92 percent of tenan...",301.0
4,4,30813_906032_2,strategic report domino’s pizza group plc ann...,3428.0,"in the spring , we launched our walk in wins’ ...",446.0
...,...,...,...,...,...,...
323,323,32825_968328_2,our performance in 2017 is our strongest on r...,1738.0,"financial performance was strong in 2017, with...",374.0
324,324,32874_969646_2,"2017 was my first full year as ceo , and it h...",1485.0,"therefore , building upon our core competencie...",385.0
325,325,32926_970385_2,4 kape technologies plc annual report and acc...,1843.0,172 percent underlying adjusted ebitda 5 kape ...,414.0
326,326,32966_971103_2,10 chariot oil gas limited annual report and ...,2770.0,with a recently stabilised oil chief executive...,377.0
327,327,33090_162245_2,23714.04 15 april 2015 10 01 am proof 8 capit...,1638.0,23714.04 15 april 2015 10 01 am proof 8 capita...,409.0

In [8]:
test_df = pd.read_csv('~/test_data_newlabel.csv')
test_df = test_df.drop(['Unnamed: 0', 'Original_Filename', 'FT_Len', 'Summary_Len'], axis=1)
test_df

,Full_Text,Summary
0,25695 19 march 2018 3 29 pm proof 7 02 s . c ...,25695 19 march 2018 3 29 pm proof 7 02 s .c .h...
1,strategic report chief executive’s statement ...,strategic report chief executive’s statement 1...
2,summary our dedication to providing our clien...,summary our dedication to providing our client...
3,"q a with ceo , david miles 92 percent of tena...","q a with ceo , david miles 92 percent of tenan..."
4,strategic report domino’s pizza group plc ann...,"in the spring , we launched our walk in wins’ ..."
...,...,...
323,our performance in 2017 is our strongest on r...,"financial performance was strong in 2017, with..."
324,"2017 was my first full year as ceo , and it h...","therefore , building upon our core competencie..."
325,4 kape technologies plc annual report and acc...,172 percent underlying adjusted ebitda 5 kape ...
326,10 chariot oil gas limited annual report and ...,with a recently stabilised oil chief executive...
327,23714.04 15 april 2015 10 01 am proof 8 capit...,23714.04 15 april 2015 10 01 am proof 8 capita...

In [9]:
test_df.rename(columns = {'Full_Text': 'article',
                                                        'Summary': 'abstract'}, inplace=True)

In [10]:
test_df

,article,abstract
0,25695 19 march 2018 3 29 pm proof 7 02 s . c ...,25695 19 march 2018 3 29 pm proof 7 02 s .c .h...
1,strategic report chief executive’s statement ...,strategic report chief executive’s statement 1...
2,summary our dedication to providing our clien...,summary our dedication to providing our client...
3,"q a with ceo , david miles 92 percent of tena...","q a with ceo , david miles 92 percent of tenan..."
4,strategic report domino’s pizza group plc ann...,"in the spring , we launched our walk in wins’ ..."
...,...,...
323,our performance in 2017 is our strongest on r...,"financial performance was strong in 2017, with..."
324,"2017 was my first full year as ceo , and it h...","therefore , building upon our core competencie..."
325,4 kape technologies plc annual report and acc...,172 percent underlying adjusted ebitda 5 kape ...
326,10 chariot oil gas limited annual report and ...,with a recently stabilised oil chief executive...
327,23714.04 15 april 2015 10 01 am proof 8 capit...,23714.04 15 april 2015 10 01 am proof 8 capita...

In [28]:
train_df, val_df = train_test_split(train_df, test_size=0.1)

In [29]:
val_df

,article,abstract
1409,chief executive officer’s statement company o...,chief executive officer’s statement company ov...
1143,punch graphix plc annual report and accounts ...,punch graphix plc annual report and accounts 2...
157,04 wolseley plc annual report and accounts 20...,04 wolseley plc annual report and accounts 201...
1492,"chief executiv e’s r epor t in 2013, challeng...","chief executiv e’s r epor t in 2013, challengi..."
2027,5 group nbt plc annual report 2010 we are ple...,5 group nbt plc annual report 2010 we are plea...
...,...,...
2696,chief executive officer’s review in this gold...,jonathan milner chief executive officer key po...
2329,annual report and accounts 2015 i 11 strategi...,profit before tax for the year increased to po...
1083,paypoint plc annual report 2012 3 chief execu...,its exible real-time functionality enables the...
703,review of activities we have made good progre...,review of activities we have made good progres...
232,chief executive’s statement our performance d...,chief executive’s statement our performance du...

In [11]:
train_df = Dataset.from_pandas(train_df)
val_df = Dataset.from_pandas(val_df)
test_df = Dataset.from_pandas(test_df)

In [13]:
train_df.save_to_disk("Downloads/HF_train_df")
val_df.save_to_disk("Downloads/HF_val_df")
test_df.save_to_disk("Downloads/HF_test_df")